Add Docker Hub build and push to CI/CD pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,67 +9,69 @@ on:
 jobs:
   validate-docker-compose:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+     - name: Checkout code
+       uses: actions/checkout@v3
 
-    - name: Validate docker-compose file
-      run: docker compose config
+     - name: Validate docker-compose file
+       run: docker compose config
 
-    - name: Check docker-compose syntax
-      run: |
-        echo  "Docker compose file is valid!"
+     - name: Check docker-compose syntax
+       run: |
+         echo  "Docker compose file is valid!"
 
   test-etl:
     runs-on: ubuntu-latest
     needs: validate-docker-compose
 
     steps:
-    - name: checkout code
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.11'
+     - name: Checkout code
+       uses: actions/checkout@v3
 
-    - name: Install dependencies
-     run: |
-        pip install pandas psycopg2-binary
+     - name: checkout code
+       uses: actions/setup-python@v4
+       with:
+         python-version: '3.11'
 
-    - name: Validate ETL script syntax
-      run: |
-        if [ -f "etl/sample_data.csv"; then
-          echo "Sample data filde found!"
-        else
-          echo "Sample data file missing!"
-          exit 1
-        fi
+     - name: Install dependencies
+       run: |
+         pip install pandas psycopg2-binary
+
+     - name: Validate ETL script syntax
+       run: |
+         if [ -f "etl/sample_data.csv"; then
+           echo "Sample data filde found!"
+         else
+           echo "Sample data file missing!"
+           exit 1
+         fi
 
   build-and-push:
     runs-on: ubuntu-latest
     needs: test-etl
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+     - name: Checkout code
+       uses: actions/checkout@v3
 
-    - name: Set up Docket Buildx
-      uses: docker/setup-buildx-action@v2
+     - name: Set up Docket Buildx
+       uses: docker/setup-buildx-action@v2
 
-    - name: Login to Docket Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+     - name: Login to Docket Hub
+       uses: docker/login-action@v2
+       with:
+         username: ${{ secrets.DOCKERHUB_USERNAME }}
+         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Build and push ETL image
-      uses: docker/build-push-action@v4
-      with:
-        context: ./etl
-        push: true
-        tags: ${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:laest,${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:${{ github.sha }}
+     - name: Build and push ETL image
+       uses: docker/build-push-action@v4
+       with:
+         context: ./etl
+         push: true
+         tags: ${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:laest,${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:${{ github.sha }}
 
-    - name: Image pushed successfully
-      run: |
-        echo "Docker image pushed to Docker Hub!"
-        echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:latest"
+     - name: Image pushed successfully
+       run: |
+         echo "Docker image pushed to Docker Hub!"
+         echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/analytics-etl:latest"
 
